translation: /resources/assets/js/i18n/%two_letters_code%.json
commit_message: '[ci skip]'
files:
  - source: /resources/lang/en/web.php
    translation: /resources/assets/js/i18n/%two_letters_code%.json
