---
version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
    - 3000:80
    volumes:
    - .:/var/www/html
    - ./contrib/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  php:
    build: .
    volumes:
    - ./storage:/var/www/html/storage
    depends_on:
    - mysql
    - redis
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=pixelfed
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - APP_KEY=${APP_KEY}
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=pixelfed
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./docker-volumes/mysql:/var/lib/mysql
  redis:
    image: redis:alpine
    volumes:
    - ./docker-volumes/redis:/data
...
